---

env:
  node: true
  browser: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 2017
  sourceType: module

extends:
  - airbnb-base
  - prettier
  - plugin:import/errors
  - plugin:import/warnings

plugins:
  - prettier

rules:
  no-console: 0
  import/no-extraneous-dependencies: [error, { devDependencies: true }]
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: all
